config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :profile, only: [:show] do
    member do
      get :new_profile
      post :create_new_profile
      put :update_profile
      patch :update_profile
      get :edit_profile
    end
  end

  resources :organizations do
    resources :employees, only: [] do
      resources :salary_slips
    end

    resources :departments do
      resources :department_employees
    end
  end

  resources :employees

  # namespace is used to group api controllers
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :organizations, only: [:index]
    end
  end

  # Defines the root path route ("/")
  root "home#index"
end

app/models/salary_slip.rb
class SalarySlip < ApplicationRecord
  belongs_to :user
  belongs_to :organization
end

app/controllers/salary_slips_controller.rb
class SalarySlipsController < ApplicationController
  layout 'dashboard'
  before_action :set_organization
  before_action :set_employee

  def index
    @pagy, @salary_slips = pagy(@employee.salary_slips)
  end

  def show
    @salary_slip = @employee.salary_slips.find(params[:id])

    pdf = SalarySlipGenerator.new(@salary_slip, @organization).generate
    file_name = "salary_slip_#{@salary_slip.for_month}.pdf"

    send_data(
      pdf.render,
      filename: file_name,
      type: 'application/pdf',
      disposition: 'inline'
    )
  end

  private

  def set_organization
    @organization = Organization.find(params[:organization_id])
  end

  def set_employee
    @employee = @organization.employees.find(params[:employee_id])
  end
end

app/helpers/salary_slips_helper.rb
module SalarySlipsHelper
end

app/views/salary_slips/index.html.erb
<nav class="flex mb-6" aria-label="Breadcrumb">
  <ol class="inline-flex items-center space-x-1 md:space-x-2 rtl:space-x-reverse">
    <li class="inline-flex items-center">
      <a href="<%= home_index_path %>" class="inline-flex items-center text-sm font-medium text-gray-700 hover:text-blue-600 dark:text-gray-400 dark:hover:text-white">
        <svg class="w-3 h-3 me-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
          <path d="m19.707 9.293-2-2-7-7a1 1 0 0 0-1.414 0l-7 7-2 2a1 1 0 0 0 1.414 1.414L2 10.414V18a2 2 0 0 0 2 2h3a1 1 0 0 0 1-1v-4a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v4a1 1 0 0 0 1 1h3a2 2 0 0 0 2-2v-7.586l.293.293a1 1 0 0 0 1.414-1.414Z"/>
        </svg>
        Home
      </a>
    </li>
    <li>
      <div class="flex items-center">
        <svg class="rtl:rotate-180 w-3 h-3 text-gray-400 mx-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
        </svg>
        <a href="<%= profile_path(@employee) %>" class="ms-1 text-sm font-medium text-gray-700 hover:text-blue-600 md:ms-2 dark:text-gray-400 dark:hover:text-white"><%= @employee.name %></a>
      </div>
    </li>
    <li>
      <div class="flex items-center">
        <svg class="rtl:rotate-180 w-3 h-3 text-gray-400 mx-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
        </svg>
        <a href="<%= organization_path(@organization) %>" class="ms-1 text-sm font-medium text-gray-700 hover:text-blue-600 md:ms-2 dark:text-gray-400 dark:hover:text-white"><%= @organization.name %></a>
      </div>
    </li>
    <li aria-current="page">
      <div class="flex items-center">
        <svg class="rtl:rotate-180 w-3 h-3 text-gray-400 mx-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
        </svg>
        <span class="ms-1 text-sm font-medium text-gray-500 md:ms-2 dark:text-gray-400">Salary Slips</span>
      </div>
    </li>
  </ol>
</nav>

<div class="salary-slips">
  <% if @salary_slips.empty? && params[:q].blank? %>
    <%= render 'shared/empty_resource', title: "No salary slip for this employee yet!", description: 'Salary slips will be created automatically by the system.', cta_url: nil %>
  <% end %>

  <div class="relative overflow-x-auto shadow-md sm:rounded-lg">

    <div class="flex items-center justify-between pb-4 bg-white dark:bg-gray-900">
      <div class="mt-5 ml-5">
        <button id="dropdownActionButton" data-dropdown-toggle="dropdownAction" class="inline-flex items-center text-gray-500 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-200 font-medium rounded-lg text-sm px-3 py-1.5 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700" type="button">
          <span class="sr-only">Filter Button</span>
          Filters
          <svg class="w-2.5 h-2.5 ml-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
          </svg>
        </button>
        <!-- Dropdown menu -->
        <div id="dropdownAction" class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700 dark:divide-gray-600">
          <ul class="py-1 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdownActionButton">
            <li>
              <%= link_to 'All', employees_path, class: 'block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white' %>
            </li>
          </ul>
        </div>
      </div>
    </div>


    <% @salary_slips.each do |slip| %>

      <div class="p-4 m-2 bg-white border border-gray-200 rounded-lg shadow sm:p-8 dark:bg-gray-800 dark:border-gray-700">
        <h5 class="text-xl font-medium text-gray-500 dark:text-gray-400"><%= slip.for_month.strftime('%B, %Y') %></h5>
        <p>Issued on <%= slip.issue_date.strftime('%d %b, %Y') %></p>
        <div class="flex mt-5 items-baseline text-gray-900 dark:text-white">
          <span class="text-3xl font-semibold">MR</span>
          <span class="text-5xl font-extrabold tracking-tight"><%= (slip.net_salary / 100).to_f %></span>
        </div>

        <div class="mt-5 flex-auto">
          <a href="<%= organization_employee_salary_slip_path(@organization, @employee, slip) %>" type="button" target="_blank" class="py-2.5 px-5 me-2 mb-2 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-100 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700">View Salary Slip</a>
          <a href="<%= organization_employee_salary_slip_path(@organization, @employee, slip) %>" type="button" target="_blank" class="py-2.5 px-5 me-2 mb-2 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-100 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700">Download</a>
        </div>
      </div>

    <% end %>


    <div class="pagy">
      <%== pagy_nav(@pagy) if @pagy.pages > 1 %>
    </div>
  </div>
</div>