config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :profile, only: [:show] do
    member do
      get :new_profile
      post :create_new_profile
      put :update_profile
      patch :update_profile
      get :edit_profile
    end
  end

  resources :organizations do
    resources :employees, only: [] do
      resources :salary_slips
    end

    resources :departments do
      resources :department_employees
    end
  end

  resources :employees

  # namespace is used to group api controllers
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :organizations, only: [:index]
    end
  end

  # Defines the root path route ("/")
  root "home#index"
end

app/models/department_employee.rb
class DepartmentEmployee < ApplicationRecord
  rolify :role_cname => 'DepartmentRole'
  belongs_to :department, counter_cache: :employees_count
  belongs_to :user

  attr_accessor :department_role

  validates :department, :user, presence: true
  validates :user_id, uniqueness: { scope: :department_id }

  validates :base_salary, numericality: { greater_than_or_equal_to: 0 }
  validates :tax, numericality: { greater_than_or_equal_to: 0 }
  validates :other_deductions, numericality: { greater_than_or_equal_to: 0 }
  validates :bonus, numericality: { greater_than_or_equal_to: 0 }

  delegate :name, to: :department, prefix: true
  delegate :name, to: :user, prefix: 'employee'
  delegate :email, to: :user, prefix: 'employee'

  accepts_nested_attributes_for :user

  after_commit :assign_department_role

  def assign_department_role
    if department_role.present? && !has_role?(department_role)
      roles.destroy_all # delete existing roles

      add_role(:"#{department_role}") if department_role.present?
    end
  end
end

app/controllers/department_employees_controller.rb
class DepartmentEmployeesController < ApplicationController
  layout 'dashboard'

  before_action :set_organization
  before_action :set_department

  def index
    @department_employees = policy_scope(@department.department_employees.includes(:user))
  end

  def show
    @department_employee = @department.department_employees.find(params[:id])
    authorize @department_employee
  end

  def new
    @department_employee = @department.department_employees.new
    authorize @department_employee

    @department_employee.build_user

    existing_employee_ids = @department.department_employees.pluck(:user_id)
    @employees = @organization.employees.where.not(id: existing_employee_ids)
  end

  def edit
    @department_employee = @department.department_employees.find(params[:id])
    authorize @department_employee

    @employee = @department_employee.user
  end

  def create
    @department_employee = @department.department_employees.new(department_employee_params)
    authorize @department_employee

    if @department_employee.save
      redirect_to organization_department_department_employees_path(@organization, @department), notice: 'Employee added to department.'
    else
      render :new
    end
  end

  def update
    @department_employee = @department.department_employees.find(params[:id])
    authorize @department_employee

    if @department_employee.update(department_employee_params)
      redirect_to organization_department_department_employees_path(@organization, @department), notice: 'Employee updated.'
    else
      render :edit
    end
  end

  def destroy
    @department_employee = @department.department_employees.find(params[:id])
    authorize @department_employee

    @department_employee.destroy

    redirect_to organization_department_department_employees_path(@organization, @department), notice: 'Employee removed from department.'
  end

  private

  def department_employee_params
    params.require(:department_employee).permit(:user_id, :designation, :description, :department_role, :base_salary, :tax, :other_deductions, :bonus, user_attributes: [:name, :email, :password, :password_confirmation, :role])
  end

  def set_organization
    @organization = policy_scope(Organization).find(params[:organization_id])
  end

  def set_department
    @department = @organization.departments.find(params[:department_id])
  end
end

app/helpers/department_employees_helper.rb
module DepartmentEmployeesHelper
end

app/views/department_employees/_form.html.erb
<%= form_for([@organization, @department, @department_employee], class: 'grid gap-2 sm:grid-cols-2 sm:gap-6') do |f| %>
  <% if @employee.blank? %>
    <div class="field">
      <label for="user_id" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Select an
        employee</label>
      <select name='department_employee[user_id]' id="user_id" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
        <option value="">Create new</option>
        <% @employees.each do |employee| %>
          <option <%= f.object.user_id == employee.id ? 'selected' : '' %> value="<%= employee.id %>"><%= employee.name %></option>
        <% end %>
      </select>
    </div>

    <div id="new_user_form" class="new-user-form">
      <%= f.fields_for :user do |ff| %>
        <div class="field">
          <%= ff.label :name, class: 'form-label' %>
          <%= ff.text_field :name, autofocus: true, class: 'form-text-input', placeholder: "Sajjad Umar", required: true %>
        </div>

        <div class="field">
          <%= ff.label :email, class: 'form-label' %>
          <%= ff.text_field :email, autofocus: true, class: 'form-text-input', placeholder: "sumar@sumartech.com", required: true %>
        </div>

        <% if @employee.blank? %>
          <div class="field">
            <%= ff.label :password, class: 'form-label' %>
            <%= ff.password_field :password, autocomplete: "new-password", class: 'form-text-input', placeholder: '••••••••', required: true %>
          </div>

          <div class="field">
            <%= ff.label :password_confirmation, class: 'form-label' %>
            <%= ff.password_field :password_confirmation, autocomplete: "new-password", class: 'form-text-input', placeholder: '••••••••', required: true %>
          </div>

          <div class="field">
            <h3 class="text-lg font-medium text-gray-900 dark:text-white">Select a global role</h3>
            <p class="mb-5 text-sm text-gray-500 dark:text-gray-400">Administrator and manager roles overrides the
              department roles.</p>
            <ul class="grid w-full gap-6 md:grid-cols-2">
              <li>
                <input type="radio" id="g-admin-role" name="department_employee[user_attributes][role]" value="admin" class="hidden peer" required <%= ff.object.is_admin? ? 'checked' : '' %>>
                <label for="g-admin-role" class="inline-flex items-center justify-between w-full p-5 text-gray-500 bg-white border border-gray-200 rounded-lg cursor-pointer dark:hover:text-gray-300 dark:border-gray-700 dark:peer-checked:text-blue-500 peer-checked:border-blue-600 peer-checked:text-blue-600 hover:text-gray-600 hover:bg-gray-100 dark:text-gray-400 dark:bg-gray-800 dark:hover:bg-gray-700">
                  <div class="block">
                    <div class="w-full text-lg font-semibold">Administrator</div>
                    <div class="w-full">Can view and manage all organizations.</div>
                  </div>
                </label>
              </li>
              <li>
                <input type="radio" id="g-manager-role" name="department_employee[user_attributes][role]" value="manager" class="hidden peer" <%= f.object.is_manager? ? 'checked' : '' %>>
                <label for="g-manager-role" class="inline-flex items-center justify-between w-full p-5 text-gray-500 bg-white border border-gray-200 rounded-lg cursor-pointer dark:hover:text-gray-300 dark:border-gray-700 dark:peer-checked:text-blue-500 peer-checked:border-blue-600 peer-checked:text-blue-600 hover:text-gray-600 hover:bg-gray-100 dark:text-gray-400 dark:bg-gray-800 dark:hover:bg-gray-700">
                  <div class="block">
                    <div class="w-full text-lg font-semibold">Organization Manager</div>
                    <div class="w-full">Can view and manage organizations they are part of.</div>
                  </div>
                </label>
              </li>
              <li>
                <input type="radio" id="g-employee-role" name="department_employee[user_attributes][role]" value="employee" class="hidden peer" <%= (ff.object.is_employee? || ff.object.roles.empty?) ? 'checked' : '' %>>
                <label for="g-employee-role" class="inline-flex items-center justify-between w-full p-5 text-gray-500 bg-white border border-gray-200 rounded-lg cursor-pointer dark:hover:text-gray-300 dark:border-gray-700 dark:peer-checked:text-blue-500 peer-checked:border-blue-600 peer-checked:text-blue-600 hover:text-gray-600 hover:bg-gray-100 dark:text-gray-400 dark:bg-gray-800 dark:hover:bg-gray-700">
                  <div class="block">
                    <div class="w-full text-lg font-semibold">Employee</div>
                    <div class="w-full">Can only manage their own profile, and the departments specified by department
                      roles.
                    </div>
                  </div>
                </label>
              </li>
            </ul>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>

  <div class="field">
    <h3 class="text-lg font-medium text-gray-900 dark:text-white">Select a role for this department</h3>
    <p class="mb-5 text-sm text-gray-500 dark:text-gray-400">Some global roles overrides the department roles.</p>
    <ul class="grid w-full gap-6 md:grid-cols-2">
      <li>
        <input type="radio" id="manager-role" name="department_employee[department_role]" value="manager" class="hidden peer" required <%= f.object.is_manager? ? 'checked' : '' %>>
        <label for="manager-role" class="inline-flex items-center justify-between w-full p-5 text-gray-500 bg-white border border-gray-200 rounded-lg cursor-pointer dark:hover:text-gray-300 dark:border-gray-700 dark:peer-checked:text-blue-500 peer-checked:border-blue-600 peer-checked:text-blue-600 hover:text-gray-600 hover:bg-gray-100 dark:text-gray-400 dark:bg-gray-800 dark:hover:bg-gray-700">
          <div class="block">
            <div class="w-full text-lg font-semibold">Manager</div>
            <div class="w-full">Can view and manage all employees within department.</div>
          </div>
        </label>
      </li>
      <li>
        <input type="radio" id="employee-role" name="department_employee[department_role]" value="employee" class="hidden peer" <%= (f.object.is_employee? || f.object.roles.empty?) ? 'checked' : '' %>>
        <label for="employee-role" class="inline-flex items-center justify-between w-full p-5 text-gray-500 bg-white border border-gray-200 rounded-lg cursor-pointer dark:hover:text-gray-300 dark:border-gray-700 dark:peer-checked:text-blue-500 peer-checked:border-blue-600 peer-checked:text-blue-600 hover:text-gray-600 hover:bg-gray-100 dark:text-gray-400 dark:bg-gray-800 dark:hover:bg-gray-700">
          <div class="block">
            <div class="w-full text-lg font-semibold">Employee</div>
            <div class="w-full">Can view and update their own profile information.</div>
          </div>
        </label>
      </li>
    </ul>
  </div>

  <div class="field">
    <%= f.label :designation, class: 'form-label' %>
    <%= f.text_field :designation, autofocus: true, class: 'form-text-input', placeholder: "CEO", required: true %>
  </div>

  <div class="field">
    <%= f.label :description, class: 'form-label' %>
    <%= f.text_field :description, autofocus: true, class: 'form-text-input', placeholder: "Manages the entire organization", required: true %>
  </div>

  <div class="field">
    <%= f.label :base_salary, class: 'form-label' %>
    <%= f.number_field :base_salary, autofocus: true, class: 'form-text-input', placeholder: "0", required: true %>
  </div>

  <div class="field">
    <%= f.label :tax, class: 'form-label' %>
    <%= f.number_field :tax, autofocus: true, class: 'form-text-input', placeholder: "0", required: true %>
  </div>

  <div class="field">
    <%= f.label :other_deductions, class: 'form-label' %>
    <%= f.number_field :other_deductions, autofocus: true, class: 'form-text-input', placeholder: "0", required: true %>
  </div>

  <div class="field">
    <%= f.label :bonus, class: 'form-label' %>
    <%= f.number_field :bonus, autofocus: true, class: 'form-text-input', placeholder: "0", required: true %>
  </div>

  <div class="field">
    <div class="actions mt-8">
      <%= f.submit "Save", class: 'button-primary mr-4' %>
      <%= link_to 'Cancel', organization_department_department_employees_path(@organization, @department), class: 'button-secondary' %>
    </div>
  </div>
<% end %>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    const new_user_form = document.getElementById('new_user_form');
    const select_user = document.getElementById('user_id');

    select_user.addEventListener('change', function() {
      const selectedUserId = select_user.value;
      if (!selectedUserId) {
        // Reload the page if no user is selected
        window.location.reload();
      } else {
        // Remove the new user form if a user is selected
        new_user_form.remove();
      }
    });
  });
</script>

app/views/department_employees/_list_row.html.erb
<tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
  <td class="px-6 py-4">
    <div class="text-base"><%= department_employee.user_id %></div>
  </td>
  <th scope="row" class="flex items-center px-6 py-4 text-gray-900 whitespace-nowrap dark:text-white">
    <div>
      <div class="text-base font-semibold"><%= department_employee.employee_name || 'N/A' %></div>
    </div>
  </th>
  <td class="px-6 py-4">
    <div class="text-base"><%= department_employee.employee_email %></div>
  </td>
  <td class="px-6 py-4">
    <div class="text-base"><%= department_employee.designation %></div>
  </td>
  <td class="px-6 py-4">
    <div class="flex items-center">
      <%= link_to 'View', organization_department_department_employee_path(organization, department, department_employee), class: "py-2 px-3 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800 mr-2" %>

      <% if policy(department_employee).update? %>
        <%= link_to 'Edit', edit_organization_department_department_employee_path(organization, department, department_employee), class: "py-2 px-3 inline-flex text-xs leading-5 font-semibold rounded-full bg-blue-100 text-blue-800 mr-2" %>
      <% end %>

      <% if policy(department_employee).destroy? %>
        <%= button_to 'Delete', organization_department_department_employee_path(organization, department, department_employee), method: :delete, data: { 'turbo-method': :delete, 'turbo-confirm': "Are you sure?"}, class: 'py-2 px-3 inline-flex text-xs leading-5 font-semibold rounded-full bg-red-100 text-red-800' %>
      <% end %>
    </div>
  </td>
</tr>

app/views/department_employees/edit.html.erb
<div class="department_employees">
  <section class="bg-white dark:bg-gray-900">
    <div class="py-8 px-4 mx-auto max-w-2xl lg:py-16">
      <h2 class="mb-4 text-xl font-bold text-gray-900 dark:text-white">Edit department employee</h2>
      <%= render 'form' %>
    </div>
  </section>
</div>

app/views/department_employees/index.html.erb
<nav class="flex mb-6" aria-label="Breadcrumb">
  <ol class="inline-flex items-center space-x-1 md:space-x-2 rtl:space-x-reverse">
    <li class="inline-flex items-center">
      <a href="<%= home_index_path %>" class="inline-flex items-center text-sm font-medium text-gray-700 hover:text-blue-600 dark:text-gray-400 dark:hover:text-white">
        <svg class="w-3 h-3 me-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
          <path d="m19.707 9.293-2-2-7-7a1 1 0 0 0-1.414 0l-7 7-2 2a1 1 0 0 0 1.414 1.414L2 10.414V18a2 2 0 0 0 2 2h3a1 1 0 0 0 1-1v-4a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v4a1 1 0 0 0 1 1h3a2 2 0 0 0 2-2v-7.586l.293.293a1 1 0 0 0 1.414-1.414Z"/>
        </svg>
        Home
      </a>
    </li>
    <li>
      <div class="flex items-center">
        <svg class="rtl:rotate-180 w-3 h-3 text-gray-400 mx-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
        </svg>
        <a href="<%= organizations_path %>" class="ms-1 text-sm font-medium text-gray-700 hover:text-blue-600 md:ms-2 dark:text-gray-400 dark:hover:text-white">Organizations</a>
      </div>
    </li>
    <li>
      <div class="flex items-center">
        <svg class="rtl:rotate-180 w-3 h-3 text-gray-400 mx-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
        </svg>
        <a href="<%= organization_path(@organization) %>" class="ms-1 text-sm font-medium text-gray-700 hover:text-blue-600 md:ms-2 dark:text-gray-400 dark:hover:text-white"><%= @organization.name %></a>
      </div>
    </li>
    <li>
      <div class="flex items-center">
        <svg class="rtl:rotate-180 w-3 h-3 text-gray-400 mx-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
        </svg>
        <a href="<%= organization_departments_path(@organization, @department) %>" class="ms-1 text-sm font-medium text-gray-700 hover:text-blue-600 md:ms-2 dark:text-gray-400 dark:hover:text-white"><%= @department.name %></a>
      </div>
    </li>
    <li aria-current="page">
      <div class="flex items-center">
        <svg class="rtl:rotate-180 w-3 h-3 text-gray-400 mx-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
        </svg>
        <span class="ms-1 text-sm font-medium text-gray-500 md:ms-2 dark:text-gray-400">Department Employees</span>
      </div>
    </li>
  </ol>
</nav>

<div class="department_employees">
  <%= render 'shared/empty_resource', title: "You don't employees in this department yet!", description: 'Add your existing employees or create a new one.', cta_url: new_organization_department_department_employee_path(@organization, @department) if @department_employees.empty?%>

  <% if @department_employees.present? %>
    <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
      <div class="flex items-center justify-between pb-4 bg-white dark:bg-gray-900">
        <div class="mt-5 ml-5">
          <button id="dropdownActionButton" data-dropdown-toggle="dropdownAction" class="inline-flex items-center text-gray-500 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-200 font-medium rounded-lg text-sm px-3 py-1.5 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700" type="button">
            <span class="sr-only">Filter Button</span>
            Filters
            <svg class="w-2.5 h-2.5 ml-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
            </svg>
          </button>
          <!-- Dropdown menu -->
          <div id="dropdownAction" class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700 dark:divide-gray-600">
            <ul class="py-1 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdownActionButton">
              <li>
                <%= link_to 'All', organizations_path, class: 'block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white' %>
              </li>
              <li>
                <%= link_to 'Active', '#', class: 'block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white' %>
              </li>
              <li>
                <%= link_to 'Inactive', '#', class: 'block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white' %>
              </li>
            </ul>
            <% if policy(@department.department_employees.new).create? %>
              <div class="py-1">
                <%= link_to 'Create New', new_organization_department_department_employee_path(@organization, @department), class: 'block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white' %>
              </div>
            <% end %>
          </div>
        </div>
        <% if policy(@department.department_employees.new).create? %>
          <div class="relative mt-5 mr-4">
            <%= link_to 'Create new', new_organization_department_department_employee_path(@organization, @department), class: 'button-primary' %>
          </div>
        <% end %>
      </div>
      <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
        <tr>
          <th scope="col" class="px-6 py-3">
            Id
          </th>
          <th scope="col" class="px-6 py-3">
            Name
          </th>
          <th scope="col" class="px-6 py-3">
            Email
          </th>
          <th scope="col" class="px-6 py-3">
            Designation
          </th>
          <th scope="col" class="px-6 py-3">
            Actions
          </th>
        </tr>
        </thead>
        <tbody>
        <% @department_employees.each do |department_employee| %>
          <%= render 'list_row', organization: @organization, department: @department, department_employee: department_employee %>
        <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
</div>

app/views/department_employees/new.html.erb
<div class="department_employees">
  <section class="bg-white dark:bg-gray-900">
    <div class="py-8 px-4 mx-auto max-w-2xl lg:py-16">
      <h2 class="mb-4 text-xl font-bold text-gray-900 dark:text-white">Add a employee to department</h2>
      <%= render 'form' %>
    </div>
  </section>
</div>

app/views/department_employees/show.html.erb
<nav class="flex mb-6" aria-label="Breadcrumb">
  <ol class="inline-flex items-center space-x-1 md:space-x-2 rtl:space-x-reverse">
    <li class="inline-flex items-center">
      <a href="<%= home_index_path %>" class="inline-flex items-center text-sm font-medium text-gray-700 hover:text-blue-600 dark:text-gray-400 dark:hover:text-white">
        <svg class="w-3 h-3 me-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
          <path d="m19.707 9.293-2-2-7-7a1 1 0 0 0-1.414 0l-7 7-2 2a1 1 0 0 0 1.414 1.414L2 10.414V18a2 2 0 0 0 2 2h3a1 1 0 0 0 1-1v-4a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v4a1 1 0 0 0 1 1h3a2 2 0 0 0 2-2v-7.586l.293.293a1 1 0 0 0 1.414-1.414Z"/>
        </svg>
        Home
      </a>
    </li>
    <li>
      <div class="flex items-center">
        <svg class="rtl:rotate-180 w-3 h-3 text-gray-400 mx-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
        </svg>
        <a href="<%= organizations_path %>" class="ms-1 text-sm font-medium text-gray-700 hover:text-blue-600 md:ms-2 dark:text-gray-400 dark:hover:text-white">Organizations</a>
      </div>
    </li>
    <li>
      <div class="flex items-center">
        <svg class="rtl:rotate-180 w-3 h-3 text-gray-400 mx-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
        </svg>
        <a href="<%= organization_path(@organization) %>" class="ms-1 text-sm font-medium text-gray-700 hover:text-blue-600 md:ms-2 dark:text-gray-400 dark:hover:text-white"><%= @organization.name %></a>
      </div>
    </li>
    <li>
      <div class="flex items-center">
        <svg class="rtl:rotate-180 w-3 h-3 text-gray-400 mx-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
        </svg>
        <a href="<%= organization_department_path(@organization, @department) %>" class="ms-1 text-sm font-medium text-gray-700 hover:text-blue-600 md:ms-2 dark:text-gray-400 dark:hover:text-white"><%= @department.name %></a>
      </div>
    </li>
    <li aria-current="page">
      <div class="flex items-center">
        <svg class="rtl:rotate-180 w-3 h-3 text-gray-400 mx-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
        </svg>
        <span class="ms-1 text-sm font-medium text-gray-500 md:ms-2 dark:text-gray-400"><%= @department_employee.employee_name %></span>
      </div>
    </li>
  </ol>
</nav>

<div class="department_employee">
  <section class="bg-white dark:bg-gray-900">
    <div class="py-2 px-4 max-w-2xl lg:py-8">
      <h2 class="font-bold"> <%= @department_employee.employee_name %> (<%= @department_employee.designation %>) </h2>
      <p class="text-gray-500 dark:text-gray-400"> <%= @department_employee.description %> </p>
      <p class="text-gray-500 dark:text-gray-400"> Email: <%= @department_employee.employee_email %> </p>
    </div>
  </section>
</div>