config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :profile, only: [:show] do
    member do
      get :new_profile
      post :create_new_profile
      put :update_profile
      patch :update_profile
      get :edit_profile
    end
  end

  resources :organizations do
    resources :employees, only: [] do
      resources :salary_slips
    end

    resources :departments do
      resources :department_employees
    end
  end

  resources :employees

  # namespace is used to group api controllers
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :organizations, only: [:index]
    end
  end

  # Defines the root path route ("/")
  root "home#index"
end

app/models/department.rb
class Department < ApplicationRecord
  belongs_to :organization

  validates :name, presence: true,  uniqueness: { scope: :organization_id }
  validates :organization, :description, presence: true

  has_many :department_employees, dependent: :destroy
  has_many :employees, through: :department_employees, source: :user

  after_commit :add_admin_to_department, if: -> { name == 'Administration' }, on: :create

  def add_user(user_id)
    department_employees.create(user_id: user_id)
  end

  private

  def add_admin_to_department
    add_user(organization.admin_user_id)
  end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  layout 'dashboard'

  before_action :set_organization

  def index
    @departments = policy_scope(@organization.departments)
  end

  def show
    @department = @organization.departments.find(params[:id])
    authorize @department
  end

  def new
    @department = @organization.departments.new
    authorize @department
  end

  def edit
    @department = @organization.departments.find(params[:id])
    authorize @department
  end

  def create
    @department = @organization.departments.new(department_params)
    authorize @department

    if @department.save
      redirect_to organization_path(@organization), notice: 'Department was successfully created.'
    else
      flash[:alert] = @department.errors.full_messages.join(', ')
      render :new
    end
  end

  def update
    @department = @organization.departments.find(params[:id])
    authorize @department

    if @department.update(department_params)
      redirect_to organization_department_path(@organization, @department), notice: 'Department was successfully updated.'
    else
      flash[:alert] = @department.errors.full_messages.join(', ')
      render :edit
    end
  end

  def destroy
    @department = @organization.departments.find(params[:id])
    authorize @department

    @department.destroy

    redirect_to organization_departments_path(@organization), notice: 'Department was successfully deleted.'
  end

  private

  def department_params
    params.require(:department).permit(:name, :description)
  end

  def set_organization
    @organization = policy_scope(Organization).find(params[:organization_id])
  end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/_form.html.erb
<%= form_for([@organization, @department], class: 'grid gap-2 sm:grid-cols-2 sm:gap-6' ) do |f| %>
  <div class="field">
    <%= f.label :name, class: 'form-label' %>
    <%= f.text_field :name, autofocus: true, class: 'form-text-input', placeholder: "Finance", required: true %>
  </div>

  <div class="field">
    <%= f.label :description, class: 'form-label' %>
    <%= f.text_field :description, autofocus: true, class: 'form-text-input', placeholder: "Driving innovation, for better tomorrow.", required: true %>
  </div>

  <div class="field">
    <div class="actions mt-8">
      <%= f.submit "Save", class: 'button-primary mr-4' %>
      <%= link_to 'Cancel', organization_path(@organization), class: 'button-secondary' %>
    </div>
  </div>
<% end %>

app/views/departments/_list_row.html.erb
<tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
  <th scope="row" class="flex items-center px-6 py-4 text-gray-900 whitespace-nowrap dark:text-white">
    <div>
      <div class="text-base font-semibold"><%= department.name %></div>
    </div>
  </th>
  <td class="px-6 py-4">
    <div class="text-base"><%= department.description %></div>
  </td>
  <td class="px-6 py-4">
    <%= link_to department.employees_count, '#', class: "py-2 px-3 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800 mr-2" %>
  </td>
  <td class="px-6 py-4">
    <div class="flex items-center">
      <%= link_to 'View', organization_department_path(organization, department), class: "py-2 px-3 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800 mr-2" %>
      <% if policy(department).update? %>
        <%= link_to 'Edit', edit_organization_department_path(organization, department), class: "py-2 px-3 inline-flex text-xs leading-5 font-semibold rounded-full bg-blue-100 text-blue-800 mr-2" %>
      <% end %>

      <% if policy(department).destroy? %>
        <%= button_to 'Delete', organization_department_path(organization, department), method: :delete, data: { 'turbo-method': :delete, 'turbo-confirm': "Are you sure?"}, class: 'py-2 px-3 inline-flex text-xs leading-5 font-semibold rounded-full bg-red-100 text-red-800' %>
      <% end %>
    </div>
  </td>
</tr>

app/views/departments/edit.html.erb
<div class="departments">
  <section class="bg-white dark:bg-gray-900">
    <div class="py-8 px-4 mx-auto max-w-2xl lg:py-16">
      <h2 class="mb-4 text-xl font-bold text-gray-900 dark:text-white">Edit Department</h2>
      <%= render 'form' %>
    </div>
  </section>
</div>

app/views/departments/index.html.erb
<nav class="flex mb-6" aria-label="Breadcrumb">
  <ol class="inline-flex items-center space-x-1 md:space-x-2 rtl:space-x-reverse">
    <li class="inline-flex items-center">
      <a href="<%= home_index_path %>" class="inline-flex items-center text-sm font-medium text-gray-700 hover:text-blue-600 dark:text-gray-400 dark:hover:text-white">
        <svg class="w-3 h-3 me-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
          <path d="m19.707 9.293-2-2-7-7a1 1 0 0 0-1.414 0l-7 7-2 2a1 1 0 0 0 1.414 1.414L2 10.414V18a2 2 0 0 0 2 2h3a1 1 0 0 0 1-1v-4a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v4a1 1 0 0 0 1 1h3a2 2 0 0 0 2-2v-7.586l.293.293a1 1 0 0 0 1.414-1.414Z"/>
        </svg>
        Home
      </a>
    </li>
    <li>
      <div class="flex items-center">
        <svg class="rtl:rotate-180 w-3 h-3 text-gray-400 mx-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
        </svg>
        <a href="<%= organizations_path %>" class="ms-1 text-sm font-medium text-gray-700 hover:text-blue-600 md:ms-2 dark:text-gray-400 dark:hover:text-white">Organizations</a>
      </div>
    </li>
    <li>
      <div class="flex items-center">
        <svg class="rtl:rotate-180 w-3 h-3 text-gray-400 mx-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
        </svg>
        <a href="<%= organization_path(@organization) %>" class="ms-1 text-sm font-medium text-gray-700 hover:text-blue-600 md:ms-2 dark:text-gray-400 dark:hover:text-white"><%= @organization.name %></a>
      </div>
    </li>
    <li aria-current="page">
      <div class="flex items-center">
        <svg class="rtl:rotate-180 w-3 h-3 text-gray-400 mx-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
        </svg>
        <span class="ms-1 text-sm font-medium text-gray-500 md:ms-2 dark:text-gray-400">Departments</span>
      </div>
    </li>
  </ol>
</nav>

<div class="ads">
  <%= render 'shared/empty_resource', title: "You don't have departments yet!", description: 'Create first department for this organization and start managing your employees.', cta_url: new_organization_department_path(@organization) if @departments.empty?%>

  <% if @departments.present? %>
    <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
      <div class="flex items-center justify-between pb-4 bg-white dark:bg-gray-900">
        <div class="mt-5 ml-5">
          <button id="dropdownActionButton" data-dropdown-toggle="dropdownAction" class="inline-flex items-center text-gray-500 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-200 font-medium rounded-lg text-sm px-3 py-1.5 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700" type="button">
            <span class="sr-only">Filter Button</span>
            Filters
            <svg class="w-2.5 h-2.5 ml-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
            </svg>
          </button>
          <!-- Dropdown menu -->
          <div id="dropdownAction" class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700 dark:divide-gray-600">
            <ul class="py-1 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdownActionButton">
              <li>
                <%= link_to 'All', organizations_path, class: 'block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white' %>
              </li>
              <li>
                <%= link_to 'Active', '#', class: 'block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white' %>
              </li>
              <li>
                <%= link_to 'Inactive', '#', class: 'block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white' %>
              </li>
            </ul>

            <% if current_user.has_role?(:admin) %>
              <div class="py-1">
                <%= link_to 'Create New', new_organization_department_path(@organization), class: 'block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white' %>
              </div>
            <% end %>

          </div>
        </div>
        <% if current_user.has_role?(:admin) %>
          <div class="relative mt-5 mr-4">
            <%= link_to 'Create new', new_organization_department_path(@organization), class: 'button-primary' %>
          </div>
        <% end %>
      </div>
      <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
        <tr>
          <th scope="col" class="px-6 py-3">
            Name
          </th>
          <th scope="col" class="px-6 py-3">
            Description
          </th>
          <th scope="col" class="px-6 py-3">
            Employees
          </th>
        </tr>
        </thead>
        <tbody>
        <% @departments.each do |department| %>
          <%= render 'list_row', organization: @organization, department: department %>
        <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
</div>

app/views/departments/new.html.erb
<div class="organizations">
  <section class="bg-white dark:bg-gray-900">
    <div class="py-8 px-4 mx-auto max-w-2xl lg:py-16">
      <h2 class="mb-4 text-xl font-bold text-gray-900 dark:text-white">Add a new department</h2>
      <%= render 'form' %>
    </div>
  </section>
</div>

app/views/departments/show.html.erb
<nav class="flex mb-6" aria-label="Breadcrumb">
  <ol class="inline-flex items-center space-x-1 md:space-x-2 rtl:space-x-reverse">
    <li class="inline-flex items-center">
      <a href="<%= home_index_path %>" class="inline-flex items-center text-sm font-medium text-gray-700 hover:text-blue-600 dark:text-gray-400 dark:hover:text-white">
        <svg class="w-3 h-3 me-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
          <path d="m19.707 9.293-2-2-7-7a1 1 0 0 0-1.414 0l-7 7-2 2a1 1 0 0 0 1.414 1.414L2 10.414V18a2 2 0 0 0 2 2h3a1 1 0 0 0 1-1v-4a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v4a1 1 0 0 0 1 1h3a2 2 0 0 0 2-2v-7.586l.293.293a1 1 0 0 0 1.414-1.414Z"/>
        </svg>
        Home
      </a>
    </li>
    <li>
      <div class="flex items-center">
        <svg class="rtl:rotate-180 w-3 h-3 text-gray-400 mx-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
        </svg>
        <a href="<%= organizations_path %>" class="ms-1 text-sm font-medium text-gray-700 hover:text-blue-600 md:ms-2 dark:text-gray-400 dark:hover:text-white">Organizations</a>
      </div>
    </li>
    <li>
      <div class="flex items-center">
        <svg class="rtl:rotate-180 w-3 h-3 text-gray-400 mx-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
        </svg>
        <a href="<%= organization_path(@organization) %>" class="ms-1 text-sm font-medium text-gray-700 hover:text-blue-600 md:ms-2 dark:text-gray-400 dark:hover:text-white"><%= @organization.name %></a>
      </div>
    </li>
    <li aria-current="page">
      <div class="flex items-center">
        <svg class="rtl:rotate-180 w-3 h-3 text-gray-400 mx-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
        </svg>
        <span class="ms-1 text-sm font-medium text-gray-500 md:ms-2 dark:text-gray-400"><%= @department.name %></span>
      </div>
    </li>
  </ol>
</nav>

<div class="organizations">
  <section class="bg-white dark:bg-gray-900">
    <div class="py-2 px-4 max-w-2xl lg:py-8">
      <h2 class="font-bold"> <%= @department.name %> </h2>
      <p class="text-gray-500 dark:text-gray-400"> <%= @department.description %> </p>
    </div>
  </section>

  <div class="employees">
    <%= render 'shared/empty_resource', title: "You don't have any employee in this department yet!", description: "Add employees to start manging them...", cta_url: new_organization_department_department_employee_path(@organization, @department) if @department.department_employees.empty?%>
    <% if policy_scope(@department.department_employees).present? %>
      <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
        <div class="flex items-center justify-between pb-4 bg-white dark:bg-gray-900">
          <div class="mt-5 ml-5">
            <h1 class="mt-4 mb-4 font-bold">Employees</h1>
            <button id="dropdownActionButton" data-dropdown-toggle="dropdownAction" class="inline-flex items-center text-gray-500 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-200 font-medium rounded-lg text-sm px-3 py-1.5 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700" type="button">
              <span class="sr-only">Filter Button</span>
              Filters
              <svg class="w-2.5 h-2.5 ml-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
              </svg>
            </button>
            <!-- Dropdown menu -->
            <div id="dropdownAction" class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700 dark:divide-gray-600">
              <ul class="py-1 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdownActionButton">
                <li>
                  <%= link_to 'All', organizations_path, class: 'block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white' %>
                </li>
                <li>
                  <%= link_to 'Active', '#', class: 'block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white' %>
                </li>
                <li>
                  <%= link_to 'Inactive', '#', class: 'block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white' %>
                </li>
              </ul>
            </div>
          </div>
          <div class="relative mt-5 mr-4">
            <%= link_to 'View all', organization_department_department_employees_path(@organization, @department), class: 'button-primary' %>
          </div>
        </div>
        <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
          <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
          <tr>
            <th scope="col" class="px-6 py-3">
              Id
            </th>
            <th scope="col" class="px-6 py-3">
              Name
            </th>
            <th scope="col" class="px-6 py-3">
              Email
            </th>
            <th scope="col" class="px-6 py-3">
              Designation
            </th>
            <th scope="col" class="px-6 py-3">
              Actions
            </th>
          </tr>
          </thead>
          <tbody>
          <% policy_scope(@department.department_employees.includes(:user)).each do |department_employee| %>
            <%= render 'department_employees/list_row', organization: @organization, department: @department, department_employee: department_employee %>
          <% end %>
          </tbody>
        </table>
      </div>
    <% end %>
  </div>
</div>