config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :profile, only: [:show] do
    member do
      get :new_profile
      post :create_new_profile
      put :update_profile
      patch :update_profile
      get :edit_profile
    end
  end

  resources :organizations do
    resources :employees, only: [] do
      resources :salary_slips
    end

    resources :departments do
      resources :department_employees
    end
  end

  resources :employees

  # namespace is used to group api controllers
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :organizations, only: [:index]
    end
  end

  # Defines the root path route ("/")
  root "home#index"
end

app/models/organization.rb
class Organization < ApplicationRecord
  belongs_to :admin_user, class_name: 'User'

  has_many :departments, dependent: :destroy
  has_many :department_employees, through: :departments
  has_many :employees, through: :department_employees, source: :user
  has_many :salary_slips, dependent: :destroy

  # we will add weekly and bi-weekly in the future
  enum salary_distribution_type: %w[monthly].index_by(&:to_s)

  after_commit :create_admin_department, on: :create

  validates :salary_distribution_day, presence: true, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 31 }
  validates :name, presence: true, uniqueness: { scope: :admin_user_id }
  validate :admin_user_must_be_admin

  private

  def create_admin_department
    departments.create(name: 'Administration', description: 'Top level administration of an organization')
  end

  def admin_user_must_be_admin
    errors.add(:admin_user, "must be an admin") unless admin_user&.has_role?(:admin)
  end
end

app/controllers/api/v1/organizations_controller.rb
class Api::V1::OrganizationsController < Api::V1::ApiController
  def index
    @organizations = policy_scope(Organization)

    render json: @organizations.as_json(only: [:id, :name], include: {
      departments: {
        only: [:id, :name, :description, :employees_count],
        include: {
          department_employees: {
            only: [:id, :designation, :description],
            include: {
              user: {
                only: [:name, :email]
              }
            }
          }
        }
      }
    })
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  layout 'dashboard'

  def index
    @pagy, @organizations = pagy(policy_scope(Organization))
  end

  def show
    @organization = policy_scope(Organization).includes(:departments).find(params[:id])
  end

  def new
    @organization = Organization.new
    authorize @organization
  end

  def edit
    @organization = policy_scope(Organization).find(params[:id])
    authorize @organization
  end

  def create
    @organization = current_user.organizations.new(organization_params)
    authorize @organization

    if @organization.save
      redirect_to organizations_path, notice: 'Organization was successfully created.'
    else
      flash[:alert] = @organization.errors.full_messages.join(', ')
      render :new
    end
  end

  def update
    @organization = policy_scope(Organization).find(params[:id])
    authorize @organization

    if @organization.update(organization_params)
      redirect_to organization_path(@organization), notice: 'Organization was successfully updated.'
    else
      flash[:alert] = @organization.errors.full_messages.join(', ')
      render :edit
    end
  end

  def destroy
    @organization = policy_scope(Organization).find(params[:id])
    @organization.destroy

    redirect_to organizations_path, notice: 'Organization was successfully deleted.'
  end

  private

  def organization_params
    params.require(:organization).permit(:name, :salary_distribution_day)
  end
end

app/helpers/api/v1/organizations_helper.rb
module Api::V1::OrganizationsHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= form_for(@organization, class: 'grid gap-2 sm:grid-cols-2 sm:gap-6' ) do |f| %>
  <div class="field">
    <%= f.label :name, class: 'form-label' %>
    <%= f.text_field :name, autofocus: true, class: 'form-text-input', placeholder: "SUMAR TECH LTD.", required: true %>
  </div>

  <div class="field">
    <%= f.label :salary_distribution_day, class: 'form-label' %>
    <%= f.text_field :salary_distribution_day, autofocus: true, class: 'form-text-input', type: 'number', placeholder: 1, required: true %>
  </div>

  <div class="field">
    <div class="actions mt-8">
      <%= f.submit "Save", class: 'button-primary mr-4' %>
      <%= link_to 'Cancel', organizations_path, class: 'button-secondary' %>
    </div>
  </div>
<% end %>

app/views/organizations/_list_row.html.erb
<tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
  <th scope="row" class="flex items-center px-6 py-4 text-gray-900 whitespace-nowrap dark:text-white">
    <div>
      <div class="text-base font-semibold"><%= organization.name %></div>
    </div>
  </th>
  <td class="px-6 py-4">
    <%= link_to organization.departments.size, organization_departments_path(organization), class: "py-2 px-3 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800 mr-2" %>
  </td>
  <td class="px-6 py-4">
    <div>
      <div class="text-base font-semibold"><%= organization.employees.size %></div>
    </div>
  </td>
  <td class="px-6 py-4">
    <div class="flex items-center">
      <%= link_to 'View', organization, class: "py-2 px-3 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800 mr-2" %>
      <% if current_user.has_role?(:admin) %>
        <%= link_to 'Edit', edit_organization_path(organization), class: "py-2 px-3 inline-flex text-xs leading-5 font-semibold rounded-full bg-blue-100 text-blue-800 mr-2" %>
        <%= button_to 'Delete', organization, method: :delete, data: { 'turbo-method': :delete, 'turbo-confirm': "Are you sure?" }, class: 'py-2 px-3 inline-flex text-xs leading-5 font-semibold rounded-full bg-red-100 text-red-800' %>
      <% end %>
    </div>
  </td>
</tr>

app/views/organizations/edit.html.erb
<div class="organizations">
  <section class="bg-white dark:bg-gray-900">
    <div class="py-8 px-4 mx-auto max-w-2xl lg:py-16">
      <h2 class="mb-4 text-xl font-bold text-gray-900 dark:text-white">Edit Organization</h2>
      <%= render 'form' %>
    </div>
  </section>
</div>

app/views/organizations/index.html.erb
<nav class="flex mb-6" aria-label="Breadcrumb">
  <ol class="inline-flex items-center space-x-1 md:space-x-2 rtl:space-x-reverse">
    <li class="inline-flex items-center">
      <a href="<%= home_index_path %>" class="inline-flex items-center text-sm font-medium text-gray-700 hover:text-blue-600 dark:text-gray-400 dark:hover:text-white">
        <svg class="w-3 h-3 me-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
          <path d="m19.707 9.293-2-2-7-7a1 1 0 0 0-1.414 0l-7 7-2 2a1 1 0 0 0 1.414 1.414L2 10.414V18a2 2 0 0 0 2 2h3a1 1 0 0 0 1-1v-4a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v4a1 1 0 0 0 1 1h3a2 2 0 0 0 2-2v-7.586l.293.293a1 1 0 0 0 1.414-1.414Z"/>
        </svg>
        Home
      </a>
    </li>
    <li aria-current="page">
      <div class="flex items-center">
        <svg class="rtl:rotate-180 w-3 h-3 text-gray-400 mx-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
        </svg>
        <span class="ms-1 text-sm font-medium text-gray-500 md:ms-2 dark:text-gray-400">Organizations</span>
      </div>
    </li>
  </ol>
</nav>


<div class="ads">
  <%= render 'shared/empty_resource', title: "You don't have organizations yet!", description: 'Create your first organization and start managing your employees.', cta_url: new_organization_path if @organizations.empty? %>
  <% if @organizations.present? %>
    <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
      <div class="flex items-center justify-between pb-4 bg-white dark:bg-gray-900">
        <div class="mt-5 ml-5">
          <button id="dropdownActionButton" data-dropdown-toggle="dropdownAction" class="inline-flex items-center text-gray-500 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-200 font-medium rounded-lg text-sm px-3 py-1.5 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700" type="button">
            <span class="sr-only">Filter Button</span>
            Filters
            <svg class="w-2.5 h-2.5 ml-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
            </svg>
          </button>
          <!-- Dropdown menu -->
          <div id="dropdownAction" class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700 dark:divide-gray-600">
            <ul class="py-1 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdownActionButton">
              <li>
                <%= link_to 'All', organizations_path, class: 'block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white' %>
              </li>
              <li>
                <%= link_to 'Active', '#', class: 'block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white' %>
              </li>
              <li>
                <%= link_to 'Inactive', '#', class: 'block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white' %>
              </li>
            </ul>
            <% if current_user.has_role?(:admin) %>
              <div class="py-1">
                <%= link_to 'Create New', new_organization_path, class: 'block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white' %>
              </div>
            <% end %>
          </div>
        </div>
        <% if current_user.has_role?(:admin) %>
          <div class="relative mt-5 mr-4">
            <%= link_to 'Create new', new_organization_path, class: 'button-primary' %>
          </div>
        <% end %>
      </div>
      <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
        <tr>
          <th scope="col" class="px-6 py-3">
            Name
          </th>
          <th scope="col" class="px-6 py-3">
            Departments
          </th>
          <th scope="col" class="px-6 py-3">
            Employees
          </th>
          <th scope="col" class="px-6 py-3">
            Actions
          </th>
        </tr>
        </thead>
        <tbody>
        <% @organizations.each do |organization| %>
          <%= render 'list_row', organization: organization %>
        <% end %>
        </tbody>
      </table>
      <%== pagy_nav(@pagy) if @pagy.pages > 1 %>
    </div>
  <% end %>
</div>

app/views/organizations/new.html.erb
<div class="organizations">
  <section class="bg-white dark:bg-gray-900">
    <div class="py-8 px-4 mx-auto max-w-2xl lg:py-16">
      <h2 class="mb-4 text-xl font-bold text-gray-900 dark:text-white">Add a new organization</h2>
      <%= render 'form' %>
    </div>
  </section>
</div>

app/views/organizations/show.html.erb
<nav class="flex mb-6" aria-label="Breadcrumb">
  <ol class="inline-flex items-center space-x-1 md:space-x-2 rtl:space-x-reverse">
    <li class="inline-flex items-center">
      <a href="<%= home_index_path %>" class="inline-flex items-center text-sm font-medium text-gray-700 hover:text-blue-600 dark:text-gray-400 dark:hover:text-white">
        <svg class="w-3 h-3 me-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
          <path d="m19.707 9.293-2-2-7-7a1 1 0 0 0-1.414 0l-7 7-2 2a1 1 0 0 0 1.414 1.414L2 10.414V18a2 2 0 0 0 2 2h3a1 1 0 0 0 1-1v-4a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v4a1 1 0 0 0 1 1h3a2 2 0 0 0 2-2v-7.586l.293.293a1 1 0 0 0 1.414-1.414Z"/>
        </svg>
        Home
      </a>
    </li>
    <li>
      <div class="flex items-center">
        <svg class="rtl:rotate-180 w-3 h-3 text-gray-400 mx-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
        </svg>
        <a href="<%= organizations_path %>" class="ms-1 text-sm font-medium text-gray-700 hover:text-blue-600 md:ms-2 dark:text-gray-400 dark:hover:text-white">Organizations</a>
      </div>
    </li>
    <li aria-current="page">
      <div class="flex items-center">
        <svg class="rtl:rotate-180 w-3 h-3 text-gray-400 mx-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
        </svg>
        <span class="ms-1 text-sm font-medium text-gray-500 md:ms-2 dark:text-gray-400"><%= @organization.name %></span>
      </div>
    </li>
  </ol>
</nav>

<div class="organizations">
  <section class="bg-white dark:bg-gray-900">
    <div class="py-2 px-4 max-w-2xl lg:py-8">
      <h2 class="font-bold"> <%= @organization.name %> </h2>
      <p class="font-normal"> Salary distribution happens  <%= @organization.salary_distribution_type %> on the <%= @organization.salary_distribution_day.ordinalize %></p>
    </div>
  </section>

  <div class="departments">
    <%= render 'shared/empty_resource', title: "You don't have departments yet!", description: 'Create first department for this organization and start managing your employees.', cta_url: new_organization_department_path(@organization) if @organization.departments.empty?%>
    <% if @organization.departments.present? %>
      <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
        <div class="flex items-center justify-between pb-4 bg-white dark:bg-gray-900">
          <div class="mt-5 ml-5">
            <h1 class="mt-4 mb-4 font-bold">Departments</h1>
            <button id="dropdownActionButton" data-dropdown-toggle="dropdownAction" class="inline-flex items-center text-gray-500 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-200 font-medium rounded-lg text-sm px-3 py-1.5 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700" type="button">
              <span class="sr-only">Filter Button</span>
              Filters
              <svg class="w-2.5 h-2.5 ml-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
              </svg>
            </button>
            <!-- Dropdown menu -->
            <div id="dropdownAction" class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700 dark:divide-gray-600">
              <ul class="py-1 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdownActionButton">
                <li>
                  <%= link_to 'All', organizations_path, class: 'block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white' %>
                </li>
                <li>
                  <%= link_to 'Active', '#', class: 'block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white' %>
                </li>
                <li>
                  <%= link_to 'Inactive', '#', class: 'block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white' %>
                </li>
              </ul>
              <div class="py-1">
                <%= link_to 'Create New', new_organization_department_path(@organization), class: 'block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white' %>
              </div>
            </div>
          </div>
          <div class="relative mt-5 mr-4">
            <%= link_to 'View all', organization_departments_path(@organization), class: 'button-primary' %>
          </div>
        </div>
        <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
          <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
          <tr>
            <th scope="col" class="px-6 py-3">
              Name
            </th>
            <th scope="col" class="px-6 py-3">
              Description
            </th>
            <th scope="col" class="px-6 py-3">
              Employees
            </th>
            <th scope="col" class="px-6 py-3">
              Actions
            </th>
          </tr>
          </thead>
          <tbody>
          <% @organization.departments.each do |department| %>
            <%= render 'departments/list_row', organization: @organization, department: department %>
          <% end %>
          </tbody>
        </table>
      </div>
    <% end %>
  </div>
</div>